### ISSUE TITLE
API for HMDB

### ISSUE THREAD

**Issue by cknoxrun** [mzmine/mzmine2#195]
Hello, I maintain the Human Metabolome Database (HMDB). It seems your software has a built in web scraper for searching metabolites by mass on HMDB. This wouldn't normally be a problem, but the requests come in very quickly and overwhelm server resources.

I'm wondering if we can work together to develop a solution? I could offer an ElasticSearch end-point / API for querying?

**Comment by tomas-pluskal** [comment]
Hi!
I am not sure what ElasticSearch is, but if you can assist with the development, I will be super-happy to replace the current "hacked" solution with a better one. Also, it would be great if the new solution worked universally for all databases from the Wishart lab, like YMDB, FooDB, etc. 
Where do we start?

**Comment by tomas-pluskal** [comment]
By the way, since HMDB now contains a lot of experimental spectra, it would be even greater if the new HMDB API allowed us to do spectral searches as well (not just mass searches).

**Comment by tomas-pluskal** [comment]
Craig, did you see my response?

**Comment by cknoxrun** [comment]
Sorry, I should be able to get something working soon (only work a couple days a week!). In the meantime the search results on mass should be faster, I added some optimizations.

**Comment by stinuss** [comment]
Hello both.
I am very interested in this topic, as we get an error every time we try to search using HMDB:
![dump](https://cloud.githubusercontent.com/assets/19661945/15666050/e77c126c-270e-11e6-9596-53d37b526c41.jpg)

Has there been any development in this regard - or is there something I can do, to prevent my users from getting this error?
Perhaps it's a network issue? Or could it be HMDB that is overburdened?

Best, Stinus

**Comment by tomas-pluskal** [comment]
Please clarify:
- Does this error appear even when you search for a single peak, or does it only appear when searching the whole peak list?
- Does it appear immediately or after the search goes on for a while
- Do you see identification results for at least some of the peaks, or no results at all
- The error does not appear when you search other databases, e.g. KEGG?

**Comment by stinuss** [comment]
Hi Tomáš.

I forwarded your questions to the user and here is his response:


1.    Does this error appear even when you search for a single peak, or does it only appear when searching the whole peak list?

ð Test of individual peaks m/z 227.1137, HMBD or KEGG, max 1 or 10 result(s) => error  message

ð Test of individual peaks m/z 301.1407, HMDB or KEGG, max 1 or 10 result(s) => error  message

ð Test of full peak list, HMDB or KEGG max 1 or 10 result(s) => error message

2.    Does it appear immediately or after the search goes on for a while

ð The comes fairly fast, 5 -20 seconds after start
3.    Do you see identification results for at least some of the peaks, or no results at all

ð No results at all
4.    The error does not appear when you search other databases, e.g. KEGG?

ð Please see 1)
I hope this helps clarifying the nature of our problem?

Venlig hilsen / Best regards

Stinus Stoumann Hoeks
Technical IT Specialist – Innovation
DuPont Nutrition & Health

Fra: Tomáš Pluskal [mailto:notifications@github.com]
Sendt: 31. maj 2016 16:01
Til: mzmine/mzmine2 <mzmine2@noreply.github.com>
Cc: Hoeks, Stinus Stoumann <STINUS.STOUMANN.HOEKS@dupont.com>; Comment <comment@noreply.github.com>
Emne: Re: [mzmine/mzmine2] API for HMDB (#195)


Please clarify:

  *   Does this error appear even when you search for a single peak, or does it only appear when searching the whole peak list?
  *   Does it appear immediately or after the search goes on for a while
  *   Do you see identification results for at least some of the peaks, or no results at all
  *   The error does not appear when you search other databases, e.g. KEGG?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/mzmine/mzmine2/issues/195#issuecomment-222697310>, or mute the thread<https://github.com/notifications/unsubscribe/ASwEecXNmAubruiqhD2tkhD-91f4Pw74ks5qHD8EgaJpZM4HP64b>.

This communication is for use by the intended recipient and contains information that may be Privileged, confidential or copyrighted under applicable law. If you are not the intended recipient, you are hereby formally notified that any use, copying or distribution of this e-mail,in whole or in part, is strictly prohibited. Please notify the sender by return e-mail and delete this e-mail from your system. Unless explicitly and conspicuously designated as "E-Contract Intended", this e-mail does not constitute a contract offer, a contract amendment, or an acceptance of a contract offer. This e-mail does not constitute a consent to the use of sender's contact information for direct marketing purposes or for transfers of data to third parties.


Francais Deutsch Italiano Espanol Portugues Japanese Chinese Korean

http://www.DuPont.com/corp/email_disclaimer.html

**Comment by tomas-pluskal** [comment]
Hi Stinus,

The HMDB and KEGG search work well for other users (including myself), so I bet there must be some networking issues on your side. Perhaps proxy or firewall configuration?

Tomas

**Comment by stinuss** [comment]
Hi Tomáš.

Thanks a lot for your efforts and help.
We will investigate internally to try to find the cause of the problem.

Venlig hilsen / Best regards

Stinus Stoumann Hoeks
Technical IT Specialist – Innovation
DuPont Nutrition & Health

Fra: Tomáš Pluskal [mailto:notifications@github.com]
Sendt: 6. juni 2016 16:46
Til: mzmine/mzmine2 <mzmine2@noreply.github.com>
Cc: Hoeks, Stinus Stoumann <STINUS.STOUMANN.HOEKS@dupont.com>; Comment <comment@noreply.github.com>
Emne: Re: [mzmine/mzmine2] API for HMDB (#195)


Hi Stinus,

The HMDB and KEGG search work well for other users (including myself), so I bet there must be some networking issues on your side. Perhaps proxy or firewall configuration?

Tomas

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/mzmine/mzmine2/issues/195#issuecomment-223981013>, or mute the thread<https://github.com/notifications/unsubscribe/ASwEeafuK-Z4bajyFnTbKkJAK97uLLBIks5qJDK_gaJpZM4HP64b>.

This communication is for use by the intended recipient and contains information that may be Privileged, confidential or copyrighted under applicable law. If you are not the intended recipient, you are hereby formally notified that any use, copying or distribution of this e-mail,in whole or in part, is strictly prohibited. Please notify the sender by return e-mail and delete this e-mail from your system. Unless explicitly and conspicuously designated as "E-Contract Intended", this e-mail does not constitute a contract offer, a contract amendment, or an acceptance of a contract offer. This e-mail does not constitute a consent to the use of sender's contact information for direct marketing purposes or for transfers of data to third parties.


Francais Deutsch Italiano Espanol Portugues Japanese Chinese Korean

http://www.DuPont.com/corp/email_disclaimer.html

**Comment by crdzl** [comment]
Hi Thomas and Craig,

I am also interested in the HMDB API project. I currently am accessing the database through direct download, but I am not sure if I will be able to publish and distribute the resulting library (if it works, of course) given that it would need access to the file (and regular updates). I was thinking to access the webpage directly, similar to MZmine, but I see now that may also be a problem, so I was wondering if the API was accessible. Thank you!


Carlos

**Comment by cknoxrun** [comment]
Sorry I don't work at the lab responsible for the HMDB anymore.

**Comment by hechth** [comment]
Has there been any changes or progress with this? Seems like there is no public web REST API or so of HMDB yet?
