### ISSUE TITLE
starting up MZmine2

### ISSUE THREAD

**Issue by graibonito** [mzmine/mzmine2#205]
I downloaded MZmine 2.19 and now have Java 1.8.0 but I get this message once I start the program:

Checking physical memory size...
Found 2032 MB memory, 64-bit system
Java version is 1.8.0_73 (64-Bit)
Java maximum heap size set to 1016 MB

Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Press any key to continue . . .

Once I press a key, the terminal closes and the application does not open

**Comment by tomas-pluskal** [comment]
Hi,

You found a curious bug! I guess nobody noticed before, because 64-bit systems with only 2GB RAM  are rare.

I will fix this issue for the next version, but in the meantime, you can edit the startMZmine.bat script and change this line
```
set HEAP_SIZE=AUTO
```
to
```
set HEAP_SIZE=1500
```

However, I definitely recommend to use a computer with more memory for running data analysis in MZmine.

**Comment by graibonito** [comment]
Thank you!
