### ISSUE TITLE
Add FWHM, tailing factor and asymmetry factor to peak list tables

### ISSUE THREAD

**Issue by dyrlund** [mzmine/mzmine2#21]
Add the following peak information to the peak list tables for QC of peaks:
- Full width at half maximum (FWHM)
- Tailing factor
- Asymmetry factor

**Comment by dyrlund** [comment]
I need to update the project loading/saving modules to account for the three new values. Should I modify the **version_2_5** or create a new version?

**Comment by tomas-pluskal** [comment]
As long as your changes don't break loading of current projects, you can just add it to the version_2_5. I think such addition should be backwards-compatible, because it doesn't change the structure of the project XML. 

But please wait until we finish updating the project loading module, otherwise we'll get merge conflicts.

**Comment by dyrlund** [comment]
Added in pull request #82.
