### ISSUE TITLE
Error of preview task

### ISSUE THREAD

**Issue by Titan100** [mzmine/mzmine2#240]
Hello,
I got error when I tried to preview chromatogram using mzmine. The error message is "Correct path to the installation directory could not be detected automatically. Please try setting manually the 'R executable path' in the project's preferences.  (Note: alternatively, the 'R_HOME' environment variable can also be use)"

New to mzmine and trying to use this for lipidomics.

Thank you.

**Comment by Titan100** [comment]
Want to add one more question. I ran mzmine in my PC (Window8, 64 bit) and try to filter the raw data. I was able to  see the preview but say R computing error while collecting data. Please see the attachment. 
Thank you for you help.

![screenshot 2016-04-16 19 34 25](https://cloud.githubusercontent.com/assets/16618391/14584241/f510ce80-040a-11e6-89c6-3705974ecb81.png)

**Comment by tomas-pluskal** [comment]
Hi,
Did you install R and all required modules, as described in the MZmine manual?

**Comment by Titan100** [comment]
Hi,
Yeah i installed all the required R packages but still did not work. I have attached the screenshot here with. The problem occurs while using baseline correction using asymmetric baseline corrector.
Thank you in advance.

Manoj

**Comment by tomas-pluskal** [comment]
Have you tried the other baseline correction algorithms? Did they work?

Gauthier @golgauth , any idea what is causing this?

**Comment by Titan100** [comment]
I could not. Here is the attachment.

[Doc2.docx](https://github.com/mzmine/mzmine2/files/226883/Doc2.docx)

**Comment by golgauth** [comment]
Nop. I have actually an intensive user feedback on the baseline correction module for a couple of month and the only one causing problems sometimes is the `RubberBand corrector`, mainly due to R limitations rather than MZmine ones. The `Asymmetric` corrector is stable. Two questions:

* Have you tried to close MZmine, terminate all potentially remaining alive processes of `Rserve` on your computer, restart MZmine and try again?
* Does the problem occur only when previewing or when you apply as well?

May be your input data cannot be processed. Could you provide a failing sample case (mzmine project) that I could use to try reproduce the problem.

**Comment by golgauth** [comment]
No answer, no test file... Cant' do anything.
