### ISSUE TITLE
2.2.1 - MS2 similarity search doesn't work on joined peaklists

### ISSUE THREAD

**Issue by photocyte** [mzmine/mzmine2#259]
Works as intended on non-joined peaklists.

May be non trivial implementation for joined?  Which MS2 is the canonical MS2 to pick etc.

**Comment by Rivas-Ubach** [comment]
Hello photocyte,

Could you solve this issue?
I am experiencing the same problem with that MS2 similarity search. There are no instructions about that function. I apply it to the aligned peak list and nothing happens.

Any update will be appreciated!
Cheers,

**Comment by photocyte** [comment]
Hello Rivas,

I added the MS2 similarity search module without much testing (and no documentation!) I haven't tried it recently, it could be horribly broken.  Does it work for you with the non-joined peaklists at least?

All the best,
-Tim

**Comment by Rivas-Ubach** [comment]
Hello Tim,

I am not sure I am performing that step well. But it seems that nothing is performed with such function. 
I am interested in exploring further the chromatograms with the MS/MS. MZmine allows metabolite identification with a Custom Database (I have one with over 500 metabolites), however I need to verify further such identifications with MS/MS. Many of the metabolites have exactly the same mass and elute at the same time, so I would need to discern them somehow.
Could the MS2 similarity search module help for verification?
Even so, nothing is performed with that function.

Thanks in advance!

Albert.

**Comment by photocyte** [comment]
Hi Albert,

What this MS2 similarity search module does is search the MS2s within a peak list against another peaklist (or, the same peaklist), and it outputs the all the ions which "matched" into the identity column of a given peak in the 1st peaklist.  It can't take MS2s from an online database (e.g. Metlin), if that is what you are interested in.

All the best,
-Tim

**Comment by Rivas-Ubach** [comment]
Hi Tim,
Thanks for the quick answer.
Yes, actually what I would love to do is a triple metabolite matching based on RT, MS1 (exact mass) and MS2 (fragmentation pattern).
According to the Metabolomics Standard Initiative (and many other scientists, me included), in order to obtain reliable identifications we need at least three independent orthogonal data. I have been using MZmine for around 5 years now and as far as I know we can only assign metabolites based on m/z and RT (in custom database search). However, this will result in putative identifications and MS/MS matching would be necessary for verification (the third orthogonal parameter).
I am not a programmer and I am not able to perform the job you do (which I appreciate very much!!). However, it would be great to include (someday) the possibility of matching metabolites using MS/MS data together with RT and m/z. I think this would be a great step forward.

Cheers!

Albert.

**Comment by tomas-pluskal** [comment]
Hi Albert,
I agree that MS2-based identification is important. The issue is simply a lack of manpower. We might have a new contributor @parthoBTK, who is interested in implementing some MS2 search functions. Maybe the Dorrestein lab could be also interested in developing something..? @lfnothias, @abisarvepalli

**Comment by lfnothias** [comment]
With recent contributions from the Dorrestein Lab to MZmine2, it is now possible to export MS/MS spectral data as MGF which can be used in GNPS (http://gnps.ucsd.edu). Allowing to perform MS/MS spectral library search against public MS/MS libraries, and molecular networking analysis. As soon the next release of MZmine2 is out, we will provide a tutorial and a typical batch file to do so.

**Comment by Rivas-Ubach** [comment]
Thank you all for your support,
I will check this way through GNPS and see what can I get for now.
I will be aware of the next release of MZmine2.

Cheers!
Albert.

**Comment by photocyte** [comment]
Hi Albert,

The bug in the MS2 similarity search module is fixed with #346, and should be available in the next release of MZmine2.  You might find this helper script I made somewhat useful for getting the data into a more easily explorable format https://github.com/photocyte/ms2_graph .  This doesn't implement your interest in MS2 identification with a custom database, but we're thinking about it.  But closing this issue since the original concern is addressed

All the best,
-Tim
