### ISSUE TITLE
Problem opening files

### ISSUE THREAD

**Issue by croy2** [mzmine/mzmine2#271]
Hello,

All MZmine versions seem to be affected. We are working on a 64-bit computer with Java version 8, update 73 (tried with update 111 too). 64-bit and R version 3.3.1.

When trying to load an MZmine file, we get this message which we did not have beforehand. Nothing changed in between the error and previously, except perhaps updates to the computer. We have tried removing the updates, but that did not solve our problem.

![erreurmzmine](https://cloud.githubusercontent.com/assets/25331035/22263964/4eafc622-e244-11e6-8645-5105cea3061c.png)

The temp MZmine files are stored on a 1T drive which is used solely for temp files, so there should be enough free space.

Do you have any idea what or where this error can come from?

Thank you,

Cynthia

**Comment by tomas-pluskal** [comment]
I have not seen this one before, but since the error talks about paging file, I would check your Windows virtual memory (paging) settings in the Control Panels. Especially make sure you have enough free space on the drive that is used for paging.

Just in case, I'd also recommend to update Java to the latest JDK (8u121), it could be a bug in the Java runtime, too.
