### ISSUE TITLE
Point 2D visualizer

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#284]
Hi @du-lab 
I wonder what is the purpose of the point 2D visualizer module that you added. It seems very slow - for the sample project that we have, it is virtually unusable (https://github.com/mzmine/sample_data/releases/download/v2.3/sample-2.3.mzmine).

**Comment by du-lab** [comment]
Hi Tomas,

The purpose of the "Point 2D Visualizer" module is to display individual data points that form a feature. It allows us to see the m/z values and retention time of these data points more easily than the original "2D visualizer".

Here I am showing two features displayed using the "2D visualizer" and the "Point 2D visualizer".

![feature_1_2d](https://cloud.githubusercontent.com/assets/13665067/24656846/13313cca-1912-11e7-8e12-d937daee6b5a.png)
![feature_1_point_2d](https://cloud.githubusercontent.com/assets/13665067/24656843/132e918c-1912-11e7-9ddd-518c5732ebab.png)
![feature_2_2d](https://cloud.githubusercontent.com/assets/13665067/24656844/132f8e2a-1912-11e7-9195-efc44d6b80fb.png)
![feature_2_point_2d](https://cloud.githubusercontent.com/assets/13665067/24656845/13302f92-1912-11e7-96b1-7e5e22d7b018.png)

We use this "Point 2D visualizer" a lot in our own work to display features.

Indeed, the "Point 2D visualizer" is much slower than the "2D visualizer" if we try to display all of the data points in a data file, but it was not designed for that purpose. 

If you would like us to remove it from MZmine 2, I am perfectly OK since users might be confused to see two similar modules implemented.

Let me know what you think.

Xiuxia

**Comment by tomas-pluskal** [comment]
Perhaps instead of having two similar modules, you could add a parameter to the current 2D visualizer (e.g. a selection of "Resample data" or "Use raw data points")?

**Comment by du-lab** [comment]
That is a good idea. We will add the selection.
