### ISSUE TITLE
ADAP deconvolution - no peaks?

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#319]
Hi,
I loaded the sample MZmine project (https://github.com/mzmine/sample_data/releases/download/v2.3/sample-2.3.mzmine) and tried to run the ADAP chromatogram deconvolution module, but it does not seem to be detecting any peaks. See the attached details.
<img width="1356" alt="screen shot 2017-06-20 at 23 14 49" src="https://user-images.githubusercontent.com/1796692/27365529-8dc21ad4-560e-11e7-81c5-7170cf1d7181.png">

**Comment by lfnothias** [comment]
Hello Tomas,
I was playing around with ADAP for LC and it works really well !
Try the following:
- S/N 5
- peak duration of 0.005 and 0.5
- using a RT wavelet range of 0.01 and 0.2. It should work better. [This parameter is really sensitive !]

**Comment by RicardoMBorges** [comment]
Can I get this opportunity to ask exactly what is the parameter wavelets from the ADAP algorithm? ...I read a paper on wavelets form chromatogram, but no success in understanding it.

**Comment by asmirn1** [comment]
Hi Ricardo,

I'm not sure that I understand your question. Which parameter are you referring to? 

If you want to read more about ADAP Chromatogram Deconvolution algorithm, then you can take a look at this paper [https://pubs.acs.org/doi/10.1021/acs.analchem.7b00947](https://pubs.acs.org/doi/10.1021/acs.analchem.7b00947)

Also, me and @duxiuxia might be able to answer your questions.

**Comment by xiaodfeng** [comment]
I come across similar problem.

**Comment by asmirn1** [comment]
@xiaodfeng 

Can you explain the problem and share a sample data file, where the ADAP deconvolution doesn't work?

**Comment by RicardoMBorges** [comment]
I didn’t find a situation where it didn’t work but I cannot define a good value for the wavelets because I don’t understand its definition. So, I keep trying random values until small peaks are found and baseline is rejected as peaks.
Thanks

**Comment by xiaodfeng** [comment]
@asmirn1 I got no error when use MZmine 2.40.1 on my laptop. However, there are only limited peaks identified by ADAP deconvolution module, which is suspicious. 
1. The Profile dataset is obtained by UPLC-Orbitrap QE.
2. Use msconvert's peak picking function to obtain Centroid dataset. This Centroid dataset has been shared to your email: asmirno1@uncc.edu.
3. Use `mass detection` module to detect masses with `noise level=10000`.
4. Use `ADAP Chromatogram Builder` module for the EIC construction, with the following parameters:

> Min group size in # of scans=3
Group intensity threshold =50000
Min highest intensity=100000
m/z tolerance=14 ppm

Altogether 1042 EICs are constructed at this step. However, I got 15434 regions of interest using CentWave peak detection in XCMS, with the following parameters:

>  ppm=14,               
    peakwidth=c(2,30),     
    snthresh = 10,        
    noise=10000, 
    prefilter=c(1, 100000)   

5. Using the constructed 1042 EICs, I performed peak picking by `ADAP Wavelets deconvolution`, with the following parameters:
> m/z center calculation=Auto
S/N threshold=10
min feature height=100000
coefficient/area threshold=100
Peak duration range=0.03-0.5 minutes
RT wavelet range=0.03-0.5 minutes

Then I got 89 chromatograms. While CentWave in XCMS got 14466 chromatograms.

6. Maybe I use a too strict peak picking parameter? Then I used a loose parameter as follows:
> m/z center calculation=Auto
S/N threshold=5
min feature height=100000
coefficient/area threshold=6
Peak duration range=0.005-0.5 minutes
RT wavelet range=0.01-0.2 minutes

Then I got 223 chromatograms this time, still a small number. I think it is OK for targeted analysis, but for un-targeted analysis. The limited chromatograms will results in lots of missing value after grouping across different samples.

7. In EIC construction step, ADAP in mzMine detected 1042 EICs, while CentWave in XCMS detected 15434 regions of interest. This may be because (1) In ADAP, one ion only belongs to one constructed EIC, while in CentWave, one ion can belong to several constructed EICs. (2) `Min group size in # of scans` and `Group intensity threshold ` are two parameters that unique in ADAP, which will further filter out the EICs from the constructed EICs.

8. In chromatograms deconvolution step, ADAP in mzMine detected 89 chromatograms, while CentWave in XCMS got 14466 chromatograms. This may because
 (1) In signal-to-noise calculation part, both ADAP and CentWave choose maximum intensity as signal, while they have different noise estimation algorithms. ADAP's noise estimation attempts to avoid overestimate from the accidental inclusion of other real peaks that may be close in RT. This is reasonable to me, however, the peaks with limited number of noise ions may be filtered out during this step.
(2) The coefficient/area threshold is also unique in ADAP, which is defined by maximum wavelet coefficient divided by the area of the peak. The maximum wavelet coefficient seems reasonable, but calculating the area of peak improperly may discard some real peaks.
(3)The `min feature height` parameter in chromatograms deconvolution step is unique in ADAP, while CentWave only has the `prefilter` parameter used in EIC construction step. I think the `min feature height` parameter will further filter out the detected peaks.

9. By the way, `ADAP chromatograms deconvolution module` is quite slow, it takes me hours to process a single file.

**Comment by asmirn1** [comment]
@xiaodfeng 

I've tried running MZmine with your parameters. 

First, after performing Mass Detection and ADAP Chromatogram Building, I've got 9881 EICs. I'm not sure why you are getting so few EICs. Could you compare all parameter values for Mass Detection and ADAP Chromatogram Building (see the figure below for my parameters).

<img width="817" alt="chromatogram parameters" src="https://user-images.githubusercontent.com/13631120/61183679-02511080-a612-11e9-94a4-680c40c29b5f.png">

Second, after running ADAP Chromatogram Deconvolution with your parameters, I've got only 568 features. This is a very low number indeed. The main reason for so few features is the parameter `RT Wavelet Range`. When I changed it to 0.00 - 0.05, I've got 5452 features (see the figure below for all parameters). As you see, ADAP Chromatogram Deconvolution is quite sensitive to parameter `RT Wavelet Range`. To find appropriate values for parameters, please use "Show preview" option in the parameter window, and you'll be able to immediately see how parameter values affect the peak-picking results.

<img width="842" alt="peak-picking parameters" src="https://user-images.githubusercontent.com/13631120/61183813-bbfcb100-a613-11e9-82c6-6bea7fcccda6.png">

Finally, regarding some other parameters... If you feel that ADAP underestimates the signal-to-noise ratio in the chromatogram deconvolution step, you can try to set a lower signal-to-noise threshold than the one in centWave (XCMS). I agree with you about the `coefficient/area threshold` - you can set it to zero if you don't want to use that parameter for filtering. Parameter `min feature height` should be easy to set up and, again, you can set it to zero if you want to completely avoid using it for filtering. Although I never tried running the ADAP chromatogram deconvolution with this parameter being zero because you may get too much noise among the produced features.

Hopefully, this will help with setting right parameters.

Alex

**Comment by xiaodfeng** [comment]
@asmirn1 Thank you for your quick reply.
1.  Using your parameters shown above, I also obtained 9881 EICs. The reason for my getting 1042 EICs is not selecting `MS1: Level 1` filter. Therefore, mzMine uses both MS1 and MS2 for EIC construction, several EICs will be linked together because of the integration of MS2. Or maybe you have a better explanation?
![image](https://user-images.githubusercontent.com/25877500/61195334-9fba4c00-a6c7-11e9-9c4c-c32d4dd20ab3.png).
2. Using your parameters shown above, I also obtained 5452 features, this is quite promising.
3. I noticed `S/N threshold` has changed from 10 to 6, and `S/N estimator` has changed from Intensity window SN into Wavelet Coeff. SN. Out of curiosity, I used the following parameters to perform feature detection again.
![image](https://user-images.githubusercontent.com/25877500/61196312-004c8780-a6ce-11e9-9486-d734369badb5.png)
Then I obtained 11149 features.

**Comment by asmirn1** [comment]
@xiaodfeng 

I'm glad that you were able to detect much more features in MZmine.

1. You are right. After removing MS1-only filter, ADAP Chromatogram builder produces only 1042 EICs. And because those EICs would have the MS1 and MS2 signal mixed together, the chromatogram deconvolution step didn't work properly.

@tomas-pluskal I've checked the original (deprecated) chromatogram builder. Its behavior is the same: if the scan filter is set to MS1-only, then Chromatogram Builder produces 6002 EICs; if the scan filter is set to All (i.e. MS1+MS2), then Chromatogram Builder produces only 16 EICs. Is this an expected behavior or a bug? Shall I display a warning message if users are building chromatograms from a mixed MS1+MS2 signal?

@xiaodfeng 

3. The signal-to-noise ratio estimated by `Wavelet Coeff SN` is usually lower then the signal-to-noise ratio estimated by `Intensity window SN`. That's why I set `S/N threshold` to 6. However, it's hard to tell which estimator is actually better. If `Intensity window SN` works for you, then definitely keep using it.

**Comment by tomas-pluskal** [comment]
@asmirn1 It is expected behavior, the chromatograms should always be constructed from the same type of scans. It might be a good idea to display a warning if the user is using mixed MS1+MS2 scans.

**Comment by asmirn1** [comment]
@tomas-pluskal Okay. I'll display a warning.

**Comment by asmirn1** [comment]
@xiaodfeng We have updated the source code, so in the future versions of MZmine you'll see a warning message when applying ADAP Chromatogram builder to both MS1 and MS2 scans. Thank you for reporting this issue!

Alex

**Comment by xiaodfeng** [comment]
@asmirn1
Great! Thank you for helping me to set the parameters properly.
Xiaodong
