### ISSUE TITLE
JVM HEAPSIZE is not changed

### ISSUE THREAD

**Issue by greentearush** [mzmine/mzmine2#398]
1. MZmine version: 2.30
2. OS version: windows 10 education / 64bit
3. Java version 1.8.0_151 
![2](https://user-images.githubusercontent.com/34765455/34291208-82f074e0-e73e-11e7-808c-a008af8049d5.JPG)

until yesterday I had been using MZmine 2.14.2 and JVM memory is correctly set as 10,000 MB (from 12GB RAM)

But as I installed the latest version 2.30, and I found it only uses 256 MB JVM memory,
even though I changed HEAP SIZE by editing parameter 'HEAP_SIZE'
![default](https://user-images.githubusercontent.com/34765455/34291315-10a48e70-e73f-11e7-9c29-0d1631dc370c.JPG)

So I tried to find the latest version which can set proper JVM memory on my PC.

and from 2.15 version, my PC cannot use 10,000 MB JVM.

I reinstalled JAVA 64 bit, and restarted my PC but it did not work.

Please let me know how I can solve this problem.

**Comment by tomas-pluskal** [comment]
Hi,
I think this is a non-issue. At some point, we changed the HEAP_SIZE meaning to specify "maximum heap size" instead of "default heap size". So even if your MZmine starts up with 256MB memory allocated for the heap, the heap size will gradually increase as more memory is needed. 
This change was made to allow people to run multiple MZmine instances at the same time, which was previously difficult on certain Windows versions if MZmine allocated too much memory on startup.

**Comment by greentearush** [comment]
Thank you for your answer

Now i figure out that i can see 256 mb only at the beginning.

I can use latest version from now on

Have a nice day

Sincerely


2017. 12. 23. 오전 1:34에 "Tomáš Pluskal" <notifications@github.com>님이 작성:
