### ISSUE TITLE
Problems with MZmine to GNPS workflow

### ISSUE THREAD

**Issue by antiburnsey** [mzmine/mzmine2#449]
Hi all,

I'm trying to use MZmine as part of the GNPS workflow for my Waters files.  Currently trying it on a single actinomycin standard so I'll know if it's worked properly, but run into a few problems.  Viewing just MS2 on the raw data file works, so the MS DDA acquisition shouldn't be at fault.

Files have been converted to .mzxml using GNPS' file converter, though also run into problems just using MSConvert.  I'm following the Feature Based Molecular Networking instructions, can attach the mzxml's if it'll be any use.  Mass detection set to just 1 for MS1 and MS2.

First issue is after Mass Detection on MS levels 1 and then 2, I get a "Scan #1 does not have a mass list" error, presumably because the UV wasn't mass detected.  Short of redoing my samples without UV detection, has anyone else had this problem?

Secondly, if I filter out UV (MS0) with MSConvert, then when it comes to the filter stage "Keep only peaks with MS2 (GNPS)", everything's removed.  Looking at the mass lists, all of the peak rows have "Show MS/MS" greyed out.  Guessing this is part of the problem.  Any suggestions on what I'm doing wrong?

Thanks,

Josh

**Comment by lfnothias** [comment]
Hi Josh,

Can you specify which MZmine version you are using.
Also, can you share the MZmine project, or one/two representative files, so we can have a look.

Louis Felix

**Comment by antiburnsey** [comment]
Hi Louis Felix,

I'm using v 2.33.  

Google drive with the project: https://drive.google.com/open?id=1Hc74mZVL6HqVule-8OAA4FPzoOdebjEp

It's got the original .raw file, the GNPS conversion, and MSConvert minus UV.

Thanks,

Josh

**Comment by lfnothias** [comment]
Hi Josh,

It looks like the problem is due to Waters data format, and MS2 is not recognised properly. I cannot really help here.  Kyo Bin might be able to help as he dealt with Waters data before.
https://groups.google.com/forum/#!category-topic/molecular_networking_bug_reports/unresolved-bugs--unknown-error-message/qjDan5zcjIY

See also Laura Sanchez post about Waters data processing. There is other posts as well.
https://groups.google.com/forum/#!searchin/molecular_networking_bug_reports/Waters%7Csort:date/molecular_networking_bug_reports/S4_rg-sf9FA/OCvT5doqEgAJ

Otherwise, I would just bring that up to Waters people.

LF

**Comment by lfnothias** [comment]
I would close that issue
