### ISSUE TITLE
Spectral library matching - Results visualizer

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine2#598]
This is a reminder that we still need to change the results visualization of the spectral library matching:

- Change metadata pane (@Annexhc )
- Change SpectralMatchIdentity (@robinschmid )
  - Save the experimental masslist + filtering steps, to visualize all filtered, matched and unmatched signals

I would suggest that we wait for this before we create next version.
My part will be done on friday, 24th 
@Annexhc  and you?

**Comment by Annexhc** [comment]
Hey Robin, I hope I will finish the spectra matching by tomorrow.
One more point regarding the spectral library matching peaklist method. The identities should be sorted by matching score.

**Comment by robinschmid** [comment]
resolved by #600

**Comment by tomas-pluskal** [comment]
<img width="1365" alt="Screen Shot 2019-05-27 at 13 19 00" src="https://user-images.githubusercontent.com/1796692/58432796-32544c80-8082-11e9-8cec-91e2c6bd6dd6.png">

A few things I noticed:
- the title of the results window remains as "Processing..."
- what is the purpose of the task controller in the bottom of the window?
- zooming is a bit weird - if I zoom the intensity scale in the top spectrum, the bottom spectrum is unchanged, so the intensities look different
- it might be better to show relative intensity (%) instead of absolute in the spectra?
- the split between the spectra and Compound Information cannot be resized using mouse

**Comment by Annexhc** [comment]
ah okay, that's weird, the processing should switch to a number of match results. The task controller was only to display the progress since it may take a while when processing a large database. In a previous version it was removed after the last task. What do you prefer? We could also remove it since the results are now added constantly from separated tasks it is not that important anymore. My first version was only using one thread ;-) But I can handle these two points for sure.
Actually I like the zooming very much as it is. I think it is good that you can zoom in each plot separately. Relative intensity makes sense!
It cannot be resized because I have switched back to a normal panel. Split pane showed kind of strange behavior. Of course we could also change back if you like it more.

**Comment by robinschmid** [comment]
We could ... 
- change to relative intensities. 
- add a button/option to couple the intensitiy axes of the mirror plot

**Comment by Annexhc** [comment]
@tomas-pluskal does the "Processing..." title remains only when you open the spectra results window from the peak list or does it also happen when you perform spectra matching with the spectra visualizer?

**Comment by Annexhc** [comment]
never mind, Ive found the bug

**Comment by Annexhc** [comment]
See PR #603

**Comment by tomas-pluskal** [comment]
<img width="1679" alt="Screen Shot 2019-05-27 at 17 03 57" src="https://user-images.githubusercontent.com/1796692/58439337-828ed700-80a1-11e9-8bf9-c01e2f2582da.png">

More comments:
- I think the spectrum is too big and cannot be resized, that is a problem - the above screenshot is with a maximized window on my 15" MacBook Pro screen.
- both Y axes are titled "rel. intensity", it is not clear which one is the spectrum and which one is library
- the colors of the title seem random - how about coloring it with some gradient by the similarity score?

**Comment by Annexhc** [comment]
oh boy yeah you are totally right about the size. I am using a 4k display, I got the dimensions all wrong I guess. I will look into it tomorrow.
I will add chance Y axis label. something like "Library [%]" should be understandable. 
Great idea with the color gradient.

**Comment by robinschmid** [comment]
We could use a static color gradient from 50% to 100% as red to green.
50% should be the minimum score that we need to expect.
This way, the colors will always represent the same score

**Comment by Annexhc** [comment]
Solved by PR #605
