### ISSUE TITLE
How to remove features that exist in blanks as well after alignment? 

### ISSUE THREAD

**Issue by QizhiSu** [mzmine/mzmine2#742]
### Basic information
Hi everybody, I am thinking if it's possible to remove features that exist in blanks as well by setting a fold change parameter? For example, those features that have peak height/area 10 times than higher than that in the blank will be kept, and the rest will be removed.

Many thanks in advance.

* My operating system:
* My MZmine version: 

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by SteffenHeu** [comment]
Hi Sukis,
I am not aware of a module like that at the moment. However, I am currently working on a module that would be able to "substract" a peak list from another. The fold change seems like a good idea to do as well. But the implementation is by no means finished yet, but I can let you know here.

**Comment by Sukis123** [comment]
@SteffenHeu Wow great! Many thanks.

**Comment by robinschmid** [comment]
Yeah, I just wanted to link out to @SteffenHeu but he was way faster than me ;)

This feature was already requested a couple of times (@lfnothias, @Annexhc ).
Maybe we can use this thread to come up with a good strategy:

### Blank removal
- use blank sample(s) to cut out **insignificant** features
- **insignificant**: Below fold-change (sample/blank < threshold) 
- Easy: Use blank features
- Comprehensive: Use blank chromatograms (to tackle issues 1 and 2)
    - highest intensity in retention time window

### Possible issues:
#### 1. Duplicates in the aligned list: 
- A feature in the blank sample can only be aligned to one feature list row. 
-  we need to make sure that the blank feature is subtracted from all "duplicates" 

#### 2. Features from noisy background signals 
- usually spanning the whole chromatograms
- random retention time
- unlikely to match blank sample even if signal intensities are on the same levels

**Comment by Annexhc** [comment]
Hey guys,
the most critical issues from my point of view are general characteristics regarding ESI, especially ion-suppression. This leads to different feature intensities when e.g. comparing a blank with a sample, because of different matrices. Anyway, the idea of using the fold change is a good start, but I am not sure if only one criteria can be used. I think we had a similar discussion before. For me, the question arises what exactly is the advantage of removing insignificant features? If one includes feature lists of blank samples in the alignment step, those insignificant features will be kind of removed when applying statistics. For me that means the mixing of 2 steps, feature list processing and statistical analysis. Don't get me wrong. It would be great to remove not relevant features like contaminants which are present in every sample and every blank, but I think we may add more issues when trying that prior to applying statistics. What do you think?

**Comment by SteffenHeu** [comment]
I was going to use the module for removing peaks that appear in an extract of a biological sample and in a spiked one to filter out the matrix peaks and only leave the ones behind, that appeared due to the spike. (at least in theory)

For that I was going to use an aligned feature list of several blank samples and give the user the option to either remove all rows that appear in every sample or just remove everything that appeared in any sample.
All your ideas seem to be able to be implemented into that.

@robinschmid 
I think noisy peaks could maybe be detected by the retention time range of the data points and continously decreasing/increasing or sustained signal intensity without any peak. But maybe this should be a seperate filter any way?

**Comment by Sukis123** [comment]
For me, I am more interested in the identification of features in samples. In practice, after alignment (including blanks), my features list contains lots of insignificant features (in blanks as well). Hence, I have to check those features one by one if they are the features that only come from my samples. In addition, those insignificant features would add uncertainty to the PCA or clustering analysis since those insignificant features are not always the same in different samples.

**Comment by SteffenHeu** [comment]
Hey guys. I have now implemented a minimal working algorithm for the subtraction. 
If works with an aligned feature list of blank measurements and the feature lists the blanks should be subtractred from. Currently I am taking the parameters m/z compared to average m/z of the blank, rt compared to avg rt and rt range compared to average rt range into account.
On top of that i would implement a fold change parameter that either works with the peak area (if rt ranges are similar) or with feature height, if the rt ranges are different but the other parameters match. The reason for the discrimination would be, that the integration borders set by MZmine go from start to end of the chromatogram and sometimes they dont, depending on the parameters of the deconvolution.

You can check the progress here: I put a lot of javadoc in there, so you can see what I am currently doing. Any suggestions or doubts?
https://github.com/SteffenHeu/mzmine2/blob/b69e12c6c9fa70aae57ceabffbd1e71713ccc71c/src/main/java/net/sf/mzmine/modules/peaklistmethods/filtering/blanksubstraction/PeakListBlankSubstractionTask.java

**Comment by robinschmid** [comment]
Sorry for the late response. I do not really get all the points. Could you restructure?

### Chromatogram retention time boundaries
- The min/max/avg boundaries for retention time are only useful after deconvolution. 
- Chromatogram rt is arbitrary 

### Working version
- your choice to separate the blanks into another aligned feature list is good. 
- rt range: how do you compare it? with a minimum overlap of X% ?

### Fold-change
- Choice for area or intensity is good. However, I would just stick to it instead of deciding for every peak.
- you can add the parameter below

``` java
  public static final ComboParameter<PeakMeasurementType> PEAK_INTENSITY =
      new ComboParameter<>("Feature intensity", "Intensity measure",
          PeakMeasurementType.values(), PeakMeasurementType.HEIGHT);
```

**Comment by tomas-pluskal** [comment]
@SteffenHeu Maybe I missed something in the previous conversation, but I don't really understand why your module takes tow separate groups of feature lists. Wouldn't it make more sense to run this module on a single aligned feature list AFTER the alignment step? The user can just select which samples (raw data files) are blank.

**Comment by benbowen** [comment]
This is great news!

For what its worth, we use the following procedure for removing features that are most likely from the blanks:

Given an aligned and gapfilled peak list, for each feature find the maximum intensity in the files from blank injections, find the maximum intensity in all non-blank files, and keep the feature if the non-blank maximum intensity is a fixed cutoff greater than the blank-files.  I typically use 3 for our setup.  This means that for each feature, there will be a non-blank file that is at least three times more intense than the most intense blank file.

I've tried various procedures based on fold change and/or significance testing, but I like the max-strategy and believe it to be more robust. I've never rigorously compared the approaches though.

**Comment by SteffenHeu** [comment]
@tomas-pluskal The first set of feature lists is used as a blank, it can either be an already aligned one or a selection of single feature lists that will be aligned in the process. The second set would be the actual samples. I thought this would be beneficial, because it might save a step. 
Your approach is a good idea, though. But this would be a minor change, which i can implement later on.
A benefit of the current method working with two sets of peak lists instead of one aligned one is, that it produces single feature lists for each measurement. This gives us the opportunity to give the user additional information via the comments in the row. For example, the comment could specify that a feature existed in the blank, but was not removed due to an intensity increase of X %. In an already aligned feature list, it would just stay there and it would be less intuitive to find out why.

I think the major questions to be answered are the parameters used for the scoring/alignment calculation, though.

@robinschmid 
1. I would assume that the feature list are deconvoluted at that point, it would not really make sense else, would it?
2. RT range is compared by the times of the scans associated with a certain the feature. For the blank the average of start and end time in the aligned blank feature list is calculated.
3. I was thinking, if it makes sense to use area most of the time, but use the maximum intensity in certain cases. For example when the rt boundaries are off to some but still acceptable degree but the average rt is spot on. This could be caused by a noisy background in the blank that gets not correctly deconvoluted or so.

**Comment by tomas-pluskal** [comment]
@SteffenHeu The reason why I don't like the current approach is because it violates good software design principles. One module should be doing one task, the task should be well defined, and the module should be doing it well. Currently your module must do some sort of alignment and background removal. I would prefer if the alignment is done by alignment modules, and your module only does background removal.

I don't really follow the argument about adding comments - you can add comments to the aligned feature list, too.

**Comment by SteffenHeu** [comment]
@tomas-pluskal Ok, I get your point.

About the comments: In an aliged feature list the comment is for the whole row, not for one specific feature. So the comment could either be too long or too unspecific to give enough information what happened to which peak. I'll just figure something out.

**Comment by robinschmid** [comment]
I usually use the height for statistics. The area can be quite off. 

### Going back to my initial answer:
Due to false deconvolution and alignment results, I think it would be the most precise method to remove sample features by searching the **blank chromatograms** or **blank mass lists** (of the corresponding scans in the _m/z_ and RT range of a sample feature.

**Comment by agent4tea7** [comment]
This is exactly what I am looking for. I am using a substrate to collect biomaterial. When extracting the sample off the substrate I get a high polymer signal peaks, this could be suppressing as well as hiding some of the meaningful features in the samples. Vendor softwares like Compound discoverer or MassHunter have blank or matrixblank subtraction - I wonder if this thread was concluded with a working solution in mzMine for the same?

Or if anyone can suggest how I can workaround mzMine workflow to remove features in blank from the sample feature lists? 

Thank you

**Comment by SteffenHeu** [comment]
It's a feature in MZmine 3: https://mzmine.github.io/mzmine_documentation/module_docs/filter_blanksubtraction/filter_blanksubtraction.html
