### ISSUE TITLE
Peak shape build 

### ISSUE THREAD

**Issue by xie753951** [mzmine/mzmine2#764]
Hello, 
This is Axe, and I'm a new user of Mzmine 2.0. I have attached one of the compounds from raw chromatography, and I'm expecting two or three peaks at 23.39, 24.60, and 25.47min, but the peak shape is really bad since the low abundance. I'm wondering if there is anything the Mzmine can do to yield better peak shape for quantitation? Thank you in advance!
![image](https://user-images.githubusercontent.com/58197583/69592643-72ea3f80-0fab-11ea-94d0-926917bc9ae7.png)

**Comment by tomas-pluskal** [comment]
It's hard to guess what your plot is actually showing. Please send us your .mzmine project file with some data and then we can take a look at it.

**Comment by xie753951** [comment]
Here is the data linkage: https://drive.google.com/open?id=1Gy7p5jZJ0RZXedJ08qo-wNqSAEUsmxcP

**Comment by tomas-pluskal** [comment]
So, if I understand correctly, your scans are acquired in profile mode but you used the "Centroid" module for mass detection. That is not going to work, because you get too many redundant masses.

<img width="1083" alt="Screen Shot 2019-11-29 at 15 07 57" src="https://user-images.githubusercontent.com/1796692/69888487-0e382900-12ba-11ea-92c5-f4774d1b3284.png">

Also, in the TIC plot it seems your signal intensity is dropping in regular intervals, so I would say something is wrong with your electrospray stability. 

<img width="1104" alt="Screen Shot 2019-11-29 at 15 08 35" src="https://user-images.githubusercontent.com/1796692/69888517-345dc900-12ba-11ea-8050-b23c4fd1d5d7.png">

As for the peak shape issue that you reported, you can try using the Feature List Methods / Feature Detection / Smooting module, but you should certainly fix the above issues first.

**Comment by xie753951** [comment]
Thank you for your suggestions! We will definitely fix the problems above and check the software again.
