### ISSUE TITLE
.xml batch files from v2.41.2 do not open in v2.53

### ISSUE THREAD

**Issue by Althalis** [mzmine/mzmine2#792]
### Basic information

* My operating system: windows 8.1 enterprise, 64-bit (tried also on Mac)
* My MZmine version: 2.41.2 and 2.53

### What happened

Hi there, 
we have installed the v2.53 but our batch files saved under v2.41.2 would not load. The window remains blank despite all endeavours (Insert, Append, Replace, Prepend...).
Any clue?
We're stuck to v2.41.2 or would need to reconfigure the whole batch file which would be sad and error-prone.
I'm attaching an example of batch file (we tried 2 different .xml batch files configured from scratch by 2 different people and both failed).

Thanks!
[mzmineBatch_v2.41.2 - Kopi.zip](https://github.com/mzmine/mzmine2/files/4159428/mzmineBatch_v2.41.2.-.Kopi.zip)

**Comment by tomas-pluskal** [comment]
This is due to a reorganization of modules in MZmine. Basically, there is no guarantee that batch files would be transferrable between MZmine versions, because the internals of the software can change. Although the internal structure doesn't change so often, it has been changing a lot recently as we are transitioning to MZmine 3 (new data model etc.).
