### ISSUE TITLE
Gap fill (same rt and mz) removes features

### ISSUE THREAD

**Issue by chandlerjd** [mzmine/mzmine2#799]
### Basic information

* My operating system: Windows 10 Pro
* My MZmine version: 2.53

### What happened

After gap-filling of an aligned feature list, a metabolite (urea, 61.0398 @ 4.4 min) is no longer present in the gap-filled list. 

![GapfillRemovesMetabolite_4](https://user-images.githubusercontent.com/32556064/74987165-938a3000-5408-11ea-81a3-f8c5eaf1658f.PNG)

![GapfillRemovesMetabolite_5](https://user-images.githubusercontent.com/32556064/74987177-99801100-5408-11ea-9628-cc19e7141ef0.PNG)

![GapfillRemovesMetabolite_1](https://user-images.githubusercontent.com/32556064/74987190-a13fb580-5408-11ea-85c6-edbd3babcb04.PNG)

![GapfillRemovesMetabolite_2](https://user-images.githubusercontent.com/32556064/74987195-a43aa600-5408-11ea-9f6c-09a0641a09fd.PNG)

![GapfillRemovesMetabolite_3](https://user-images.githubusercontent.com/32556064/74987205-a69d0000-5408-11ea-9772-121f76af9af9.PNG)

**Comment by tomas-pluskal** [comment]
Interesting. Could you upload the .mzmine project file, so we can take a look?

**Comment by chandlerjd** [comment]
Here is a DropBox link.

https://www.dropbox.com/s/ay0sx6r3tof9az5/20200221_project-gapfillerror.mzmine?dl=0

**Comment by chandlerjd** [comment]
I will e-mail you a link to download the project file.

**Comment by tomas-pluskal** [comment]
I checked your project file. It turns out your peaks have not disappeared, you can still find your urea after gap filling (look for peak ID 1770). I guess you missed it because the m/z value was changed to 61.0412 m/z. That is because the average m/z value takes into account the new data found during gap filling. To avoid this error, you should use lower mass tolerance window during gap filling (e.g., instead of 5 ppm use 1 ppm or even 0 ppm).

**Comment by chandlerjd** [comment]
That makes sense - thank you for the cogent explanation! I will lower the ppm threshold when gap filling.

**Comment by chandlerjd** [comment]
Apparently ppm value cannot be set as 0. At 0.1 and 1 ppm, the issue persists (urea m/z is shifted by ~22 ppm from the originally observed value).

**Comment by tomas-pluskal** [comment]
Okay, in that case it means the existing peaks (in the same row id 1770) have a wide distribution of m/z values (across their whole chromatograms). During the gap filling, the whole m/z range of the existing peaks is taken into account. 

Look at this scan for example, where a wrong mass is used to build your urea chromatogram, just because it is higher than the actual urea ion:

<img width="1332" alt="Screen Shot 2020-02-25 at 09 04 56" src="https://user-images.githubusercontent.com/1796692/75202228-efa8d780-57ad-11ea-8af5-84a89d814b4d.png">

What m/z tolerance did you set during your chromatogram building step?
You will need to set that one lower.

**Comment by chandlerjd** [comment]
I use the ADAP chromatogram builder. I used 0.01 m/z tolerance (total window size 0.02 m/z) before, but tried again with 0.005 (total window size 0.01 m/z). The Du Lab manual for ADAP recommends using the 0.01 m/z tolerance setting, which is why I chose this. This time I don't see a big problem with the m/z of urea after gap filling. It's interesting that this works as the false match you pointed out above is still within the threshold as I understand it. 

I guess I will use 0.005 m/z moving forward and look out for this error in future datasets. What is the danger in setting the tolerance too low - false missed scans?

![GapfillRemovesMetabolite_8](https://user-images.githubusercontent.com/32556064/75263764-6d73df80-57bc-11ea-8866-65bb9f0156cd.PNG)

![GapfillRemovesMetabolite_6](https://user-images.githubusercontent.com/32556064/75263774-706ed000-57bc-11ea-996d-9026c2afee56.PNG)

![GapfillRemovesMetabolite_7](https://user-images.githubusercontent.com/32556064/75263782-72d12a00-57bc-11ea-9b4f-1751878e1fd0.PNG)

**Comment by tomas-pluskal** [comment]
With m/z tolerance set to 0.005 the false match is not in the window anymore (61.0479 is not within 61.0399 +- 0.005).

The optimal setting of the m/z tolerance for chromatogram builder depends on the m/z accuracy of your instrument. Check how much your m/z values differ from scan to scan.

**Comment by chandlerjd** [comment]
Thanks!
