### ISSUE TITLE
Feature list for FBMN

### ISSUE THREAD

**Issue by ogomaa** [mzmine/mzmine2#813]
### Basic information

* My operating system: Windows 64 bit
* My MZmine version: 2.53

### What happened

I am processing a data file for a pure commercial metabolite (precursor mass m/z 614.3004). The raw data acquired by Agilent qTOF was converted to mzXML format using msconvert software. Then, I followed the steps as mentioned in the youtube video tutorial including Mass detection, Chromatogram builder, Spectral deconvolution, Peak isotopic group and peak alignment. When I filter the features to include those containing MS/MS data for GNPS, I lose most of the features of interest.
I attached the MZmine project in order to identify the mistake in the workflow.
* Please upload an MZmine project file that demonstrates the problem you are reporting. https://www.dropbox.com/s/is8mi1uvb4ogv2h/Streptomycin_Cpd.mzmine?dl=0

Thanks,
Osama

**Comment by robinschmid** [comment]
Hey Osama,

I would recommend converting to mzML as it is the newer data standard. (This should not change much but only for future projects)

Did you apply spectral deconvolution or chromatogram deconvolution? The correct step is chromatogram deconvolution - to split chromatograms to features. (It seems you are doing it right - but you miss mentioned the spectral deconvolution module).

Did you try to use a wider pairing width for retention time and m/z during deconvolution? 
Do you know that you have MS2 scans for these features in your file?

**Comment by ogomaa** [comment]
Hi Robin,
Thanks for your reply.
I am using msconvert to convert data files (acquired in centroid mode) to mzXML, I will choose mzML for future projects. Does the msconvert parameters (binary encoding precision, usezlib compression, and peak picking) affect the MZmine 2 workflow?

I did chromatogram deconvolution. In this regard, how can I identify the parameters I used in a saved project?
In my analysis method, I am subjecting two precursors from each MS1 to 3 collision energies to get MS2 data. As a result, I have 6 MS2 spectral scans for each MS1 spectrum (see screenshot https://www.dropbox.com/s/qdji9p1bl5hfy5m/Screenshot%20%282%29.png?dl=0). Does chromatogram builder pair only one MS2 spectrum for each MS1 spectrum? if yes, which one does it pair?

For wider pairing width for RT and m/z, I usually use 0.1 min for RT and 0.02 for m/z. As seen in the screenshot at RT 0.36, the MS2 spectra are in this range.

Thanks and looking forward to hearing from you.

**Comment by robinschmid** [comment]
I think the msconvert parameters should not change anything. (I mean apart from change in precision of your mz/retention time and intensity with compression)

Never done that, but I think you can access parameters of a feature list by right click/info.

I have checked your project file. You have multiple MS2 spectra of the same precursors. In total, 4 precursors have been subjected to MS2 analysis. To increase the coverage you could apply dynamic exclusion during acquisition. All MS2 spectra within mz and retention time range are grouped with the MS1 features during Chromatogram deconvolution. Otherwise you can also use the feature list methods/filter/group MS2 scans module to reassign all MS2 to their features with different settings. You can explore the MS2 spectra with the options below. Or export to SIRIUS function will export all MS2 spectra. 

I have created two batch files that you can use and adjust. If you are performing loop injections/direct injection - you could also leave out the deconvolution step and instead pair the MS2 spectra directly with the chromatograms (see difference in batch files)

[mzmine_batches.zip](https://github.com/mzmine/mzmine2/files/4475259/mzmine_batches.zip)

1. Feature list filtered by features with MS2
2. Right click/Show/All MS/MS for 614.299
3. Right click/Show/Most intense MS/MS for all rows
![image](https://user-images.githubusercontent.com/10366914/79224577-9ed36800-7e5b-11ea-90a4-1388fb3e6da4.png)
![image](https://user-images.githubusercontent.com/10366914/79224643-c0345400-7e5b-11ea-96e3-490c1a939b2d.png)
![image](https://user-images.githubusercontent.com/10366914/79224706-dd692280-7e5b-11ea-8b91-9c22deb619f1.png)

**Comment by robinschmid** [comment]
I guess it is resolved
