### ISSUE TITLE
Not detecting a metabolite at liberal thresholds

### ISSUE THREAD

**Issue by chandlerjd** [mzmine/mzmine2#839]
### Basic information

* My operating system: Windows 10 
* My MZmine version: 2.53

### What happened

* Please describe what happened and how it differs from what you expected to happen.
I can see a known metabolite is in the masses of a sample. MZmine 2.53 doesn't detect it even at liberal settings. I would like to know what I am doing wrong - this is an important metabolite I don't want to miss, and it appears easy to spot in the mass trace.

* Please include all parameter values for the MZmine modules you used. 
Feature of interest 166.0532 m/z
![20200709_MZmine2 53_MetO-nonedetection-1](https://user-images.githubusercontent.com/32556064/87083829-42ce7480-c1fb-11ea-883e-b00a37d4f9a1.png)

Looking for it in the chromatograms
![20200709_MZmine2 53_MetO-nonedetection-2](https://user-images.githubusercontent.com/32556064/87083868-4f52cd00-c1fb-11ea-804d-17c0a5d147d6.png)

Mass detection method
![20200709_MZmine2 53_MetO-nonedetection-3](https://user-images.githubusercontent.com/32556064/87083890-5679db00-c1fb-11ea-90d1-f2db5ad93c31.png)

Chromatogram builder method
![20200709_MZmine2 53_MetO-nonedetection-4](https://user-images.githubusercontent.com/32556064/87084343-136c3780-c1fc-11ea-8cfa-a815a240b1bf.png)

* Project file
Available on request, I can't upload it here.

**Comment by SteffenHeu** [comment]
Is your raw data profile or centroided?
If it's profile: did you try mass detection using the Exact Mass mass detector? I don't have any experience using Wavelet transform, but exact mass has worked very well for me.
If it is centroided: use the centroid mass detector

Maybe your m/z tolerance is too high so it get's assigned to a wrong XIC. How would the XIC for 166.0678 +- 0.005 look like? The range would be 166.0628 - 166.0728, so the two features ranges overlap during chromatogram detection, so your targeted feature does not include enough data points in a row because they get partially assigned to 166.0678. How bigis your mass accuracy inbetween scans? Did you try lower mz tolerances during chromatogram building?

**Comment by chandlerjd** [comment]
Thanks for your reply.

The data are in profile mode. I tried with Exact Mass, and it reproduces the same chromatogram (still using ADAP chromatogram builder).

Here is the 0.005 m/z window around the target mass (the feature of interest is at 9.7 min):
![20200714_mzmine2_meto-detection_troubleshoot](https://user-images.githubusercontent.com/32556064/87457334-2f921f00-c5d6-11ea-8b33-e94bf8e5ec20.gif)


And the 5 ppm window:
![20200714_mzmine2_meto-detection_troubleshoot-5ppmXIC](https://user-images.githubusercontent.com/32556064/87457351-36b92d00-c5d6-11ea-9367-31e4b653b492.gif)

**Comment by chandlerjd** [comment]
I deconvoluted the exact mass data and this did detect the peak of interest after all; I was overlooking the fact that the 166.0531 m/z peaks would be deconvolved downstream. I am not sure if this means everything in the workflow is now fine (I do detect the feature of interest, after all), or perhaps it is concerning that I could have grouped two peaks that were not time-resolved into one mass? (Say 166.0578 and 166.0532 were both eluting at the same time and had been grouped in the initial chromatogram detection step, as they were here?)

**Comment by SteffenHeu** [comment]
>  [...] or perhaps it is concerning that I could have grouped two peaks that were not time-resolved into one mass? (Say 166.0578 and 166.0532 were both eluting at the same time and had been grouped in the initial chromatogram detection step, as they were here?)

Yes, i think that could have happened. Generally i would not choose higher tolerances than you actually need. You could look at the scans at rt ~9.5min where your compound elutes and check the mass deviation between scans to set the m/z tolerance parameter for the ADAP chromatogram builder. If the 5 ppm window works for you, i would go with 5ppm rather than 0.005 which is huge for instruments which are reasonably state-of-the-art.

**Comment by chandlerjd** [comment]
I think it was this guidance from the ADAP user manual that led me to the 0.005 m/z value originally:

> m/z tolerance: Maximum m/z difference of data points in consecutive scans in order to
be connected to the same chromatogram. Twice the m/z tolerance set by the user is the
maximum width of a mass trace. **We strongly recommend setting the m/z value and not the
ppm value.** Whichever value is set to 0.0 will not be used.

At expected 166.0532 m/z, 5 ppm (typical Orbitrap mass accuracy threshold) could reasonably vary by +/-0.0008 m/z. So 0.0050 m/z is indeed too generous. But go up to something larger like glutathione disulfide (613.1592 m/z) and now 5 ppm tolerance is equivalent to around 0.0031 m/z. Still, the Orbitrap usually exhibits more like 1-2 ppm mass accuracy in practice, so I could probably bring the threshold down a bit. And it may be worth exploring the ppm threshold for my data.

**Comment by chandlerjd** [comment]
This manuscript explains how m/z came to be the recommended way to construct chromatograms in the ADAP method: https://pubmed.ncbi.nlm.nih.gov/28752754/

However, I'll do some experimenting with ppm. I am closing the topic now. Thank you, SteffenHeu, for your nice suggestions.
